apiVersion: v1
kind: Namespace
metadata:
  name: gaia-reserved

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: gaia
  namespace: {{ .Release.Namespace }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gaia-resource-deployer
  namespace: {{ .Release.Namespace }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gaia
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: pml-manager
spec:
  selector:
    matchLabels:
      control-plane: pml-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: pml-manager
    spec:
      containers:
        - name: gaia
          image: lmxia/gaia:{{ .Values.image.tag }}
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
      serviceAccountName: gaia

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gaia-scheduler
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: pml-manager
spec:
  selector:
    matchLabels:
      control-plane: pml-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: pml-manager
    spec:
      containers:
        - name: gaia
          image: lmxia/gaia-scheduler:{{ .Values.image.tag }}
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
      serviceAccountName: gaia