apiVersion: {{ include "common.capabilities.rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  name: gaia-manager
rules:
  - apiGroups: [ "*" ]
    resources: [ "*" ]
    verbs: [ "*" ]
  - nonResourceURLs: [ "*" ]
    verbs: [ "get" ]

---
apiVersion: {{ include "common.capabilities.rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  name: clusternet:hub
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gaia-manager
subjects:
  - kind: ServiceAccount
    name: gaia
    namespace: {{ .Release.Namespace }}
