apiVersion: apps.gaia.io/v1alpha1
kind: Description
metadata:
  name: case0
  namespace: gaia-reserved
spec:
  appID: appID-case0
  components:
    - name: component1
      namespace: test1
      runtimeType: runc
      workload:
        workloadtype: deployment
        traitDeployment:
          replicas: 10
      module:
        metadata:
          labels:
            app: nginx
        spec:
          containers:
            - name: nginx
              image: nginx:1.14.2
              ports:
                - containerPort: 80
              resources:
                limits:
                  cpu: "2"
                  memory: "1Gi"
                requests:
                  cpu: "1"
                  memory: "10Mi"
    - name: component2
      namespace: test2
      runtimeType: kata
      workload:
        workloadtype: deployment
        traitDeployment:
          replicas: 10
      module:
        metadata:
          labels:
            app: nginx
        spec:
          containers:
            - name: nginx
              image: nginx:1.14.2
              ports:
                - containerPort: 80
              resources:
                limits:
                  cpu: "2"
                  memory: "1Gi"
                requests:
                  cpu: "1"
                  memory: "10Mi"
