apiVersion: apps.gaia.io/v1alpha1
kind: Description
metadata:
  name: case1
  namespace: gaia-reserved
spec:
  appID: appID-case1
  components:
    - name: component1
      namespace: test1
      runtimeType: runc
      workload:
        workloadtype: affinitydaemon
        traitaffinitydaemon:
          sn: sn1
      module:
        metadata:
          labels:
            app: nginx
        spec:
          containers:
            - name: nginx
              image: nginx:1.14.2
              ports:
                - containerPort: 80
              resources:
                limits:
                  cpu: "500m"
                  memory: "100Mi"
                requests:
                  cpu: "500m"
                  memory: "100Mi"
    - name: component2
      namespace: test2
      runtimeType: runc
      schedulePolicy:
        netenvironment:
          matchExpressions:
            - { key: net-environment, operator: In, values: [ "core" ] }
        geolocation:
          matchExpressions:
            - { key: geo-location, operator: In, values: [ "beijing" ] }
        provider:
          matchExpressions:
            - { key: supplier-name, operator: In, values: [ "aliyun" ] }
      workload:
        workloadtype: deployment
        traitDeployment:
          replicas: 10
      module:
        metadata:
          labels:
            app: nginx
        spec:
          containers:
            - name: nginx
              image: nginx:1.14.2
              ports:
                - containerPort: 80
              resources:
                limits:
                  cpu: "500m"
                  memory: "100Mi"
                requests:
                  cpu: "500m"
                  memory: "100Mi"
