apiVersion: apps.gaia.io/v1alpha1
kind: Description
metadata:
  name: case4
  namespace: gaia-reserved
spec:
  appID: appID-case4
  components:
    - name: serss
      namespace: default
      runtimeType: runc
      schedulePolicy: { }
      workload:
        workloadtype: serverless
        traitServerless:
          miniInstancenumber: 1
          threshold: "{\"cpuMin\":20,\"cpuMax\":70,\"memMin\":20,\"memMax\":80,\"qpsMin\":40,\"qpsMax\":80}"
          step: 1
      module:
        metadata:
          labels:
            app: serss
        spec:
          containers:
            - name: serss
              image: 172.17.9.231:8880/hyperio/app:latest
              resources:
                limits:
                  cpu: "100m"
                  memory: "100Mi"
                requests:
                  cpu: "100m"
                  memory: "100Mi"