
---
apiVersion: apps.gaia.io/v1alpha1
kind: Description
metadata:
  finalizers:
    - apps.gaia.io/finalizer
  name: test
  namespace: gaia-reserved
spec:
  appID: appID1
  components:
    - name: component1
      namespace: test
      runtimeType: runc
      workload:
        workloadtype: serverless
      schedulePolicy:
      module:
        metadata:
          labels:
            app: nginx
        spec:
          containers:
            - name: nginx
              image: nginx:1.14.2
              ports:
                - containerPort: 80
    - name: component2
      namespace: test2
      runtimeType: runc
      schedulePolicy:
        specificResource:
            matchExpressions:
              - { key: sn, operator: In, values: [ "sn1", "sn2" ] }
      workload:
        workloadtype: deployment
        traitDeployment:
          replicas: 3
      module:
        metadata:
          labels:
            app: nginx
        spec:
          containers:
            - name: nginx
              image: nginx:1.14.2
              ports:
                - containerPort: 80


