apiVersion: apps.gaia.io/v1alpha1
kind: NetworkRequirement
metadata:
  name: case5
  namespace: gaia-reserved
spec:
  networkCommunication:
    - name: case5-component1
      selfID:
        - /pml/case5/c1/1
      interSCNID:
        - source:
            id: /pml/case5/c1/1
            attributes:
              - key: POLICY_SOURCE
                value: policy_inst1
          destination:
            id: /pml/case5/c2/1
            attributes:
              - key: POLICY_DEST
                value: policy_inst2
          sla:
            delay: 100
            lost: 100
            jitter: 999999
            bandwidth: 10
          providers:
            - a
            - b
            - c
    - name: case5-component2
      selfID:
        - /pml/case5/c2/1
      interSCNID:
        - source:
            id: /pml/case5/c2/1
            attributes:
              - key: POLICY_SOURCE
                value: policy_inst1
          destination:
            id: /pml/case5/c1/1
            attributes:
              - key: POLICY_DEST
                value: policy_inst2
          sla:
            delay: 100
            lost: 100
            jitter: 999999
            bandwidth: 10
          providers:
            - a
            - b
            - c
    - name: case5-component3
      selfID:
        - /pml/case5/c3/1