apiVersion: apps.gaia.io/v1alpha1
kind: NetworkRequirement
metadata:
  name: case2
  namespace: gaia-reserved
spec:
  networkCommunication:
    - name: case2-component1
      selfID:
        - /pml/case2/c1/1
        - /pml/case2/c1/2
        - /pml/case2/c1/3
        - /pml/case2/c1/4
        - /pml/case2/c1/5
        - /pml/case2/c1/6
      interSCNID:
        - source:
            id: /pml/case2/c1/1
            attributes:
              - key: POLICY_SOURCE
                value: policy_inst1
          destination:
            id: /pml/case2/c2/1
            attributes:
              - key: POLICY_DEST
                value: policy_inst2
          sla:
            delay: 999999
            lost: 100
            jitter: 999999
            bandwidth: 8
          providers:
            -  jiangnan-fabric-101
            -  jiangnan-fabric-102
            -  jiangnan-fabric-103
        - source:
            id: /pml/case2/c1/3
            attributes:
              - key: POLICY_SOURCE
                value: policy_inst1
          destination:
            id: /pml/case2/c4/1
            attributes:
              - key: POLICY_DEST
                value: policy_inst2
          sla:
            delay: 999999
            lost: 100
            jitter: 999999
            bandwidth: 8
          providers:
            -  jiangnan-fabric-101
            -  jiangnan-fabric-102
            -  jiangnan-fabric-103
        - source:
            id: /pml/case2/c1/4
            attributes:
              - key: POLICY_SOURCE
                value: policy_inst1
          destination:
            id: /pml/case2/c5/1
            attributes:
              - key: POLICY_DEST
                value: policy_inst2
          sla:
            delay: 999999
            lost: 100
            jitter: 999999
            bandwidth: 8
          providers:
            -  jiangnan-fabric-101
            -  jiangnan-fabric-102
            -  jiangnan-fabric-103
        - source:
            id: /pml/case2/c1/5
            attributes:
              - key: POLICY_SOURCE
                value: policy_inst1
          destination:
            id: /pml/case2/c6/1
            attributes:
              - key: POLICY_DEST
                value: policy_inst2
          sla:
            delay: 999999
            lost: 100
            jitter: 999999
            bandwidth: 8
          providers:
            -  jiangnan-fabric-101
            -  jiangnan-fabric-102
            -  jiangnan-fabric-103
    - name: case2-component2
      selfID:
        - /pml/case2/c2/1
    - name: case2-component3
      selfID:
        - /pml/case2/c3/1
    - name: case2-component4
      selfID:
        - /pml/case2/c4/1
    - name: case2-component5
      selfID:
        - /pml/case2/c5/1
    - name: case2-component6
      selfID:
        - /pml/case2/c6/1